@extends('layouts.tablerpublic')

@section('content')
@include('publicviews.statistik.partials.berusaha-stats', [
  'pageTitle' => 'Statistik Publik Izin',
  'pageDescription' => 'Ringkasan data izin berdasarkan status perizinan, kewenangan, dan sektor.',
  'primaryMetricLabel' => 'Total Izin Tahun ' . $year,
  'primaryMetricValue' => number_format($total ?? 0),
  'primaryMetricNote' => 'Total izin pada tahun terpilih.',
  'secondaryMetricLabel' => 'Total Periode Tampil',
  'secondaryMetricValue' => number_format($totalTerbit ?? 0),
  'secondaryMetricNote' => 'Sesuai semester yang dipilih.',
  'thirdMetricLabel' => 'NIB / KBLI Unik',
  'thirdMetricValue' => number_format($totalNib ?? 0) . ' / ' . number_format($totalKbli ?? 0),
  'thirdMetricNote' => 'Identitas usaha yang terhubung.',
  'fourthMetricLabel' => 'Total Dokumen',
  'fourthMetricValue' => number_format($totalDokumen ?? 0),
  'fourthMetricNote' => 'Nama dokumen yang tercatat.',
  'categoryTitle' => 'Top Status Perizinan',
  'categorySubtitle' => 'Status izin paling dominan.',
  'categoryAllTitle' => 'Daftar status perizinan',
  'secondaryTitle' => 'Top Kewenangan',
  'secondarySubtitle' => 'Kewenangan penerbitan terbanyak.',
  'secondaryAllTitle' => 'Daftar kewenangan',
  'monthlyTitle' => 'Jumlah Izin per Bulan',
  'yearlyTitle' => 'Izin per tahun',
  'secondaryYearlyTitle' => 'Sektor per tahun',
  'stackedTitle' => 'Komposisi status perizinan per bulan',
  'donutTitle' => 'Top status perizinan',
  'detailModalTitle' => 'Rincian status perizinan',
  'detailColumnLabel' => 'Status Perizinan',
  'categoryRows' => $stats,
  'secondaryRows' => $secondaryStats,
  'topItems' => $topKategori,
  'detailDataByMonth' => [],
  'secondarySeriesByYear' => $secondarySeriesByYear,
  'allSecondary' => $allSecondary,
  'allKategori' => $allKategori,
  'kategoriSeries' => $kategoriSeries,
  'monthlyCounts' => $monthlyCounts,
  'yearlyCounts' => $yearlyCounts,
  'monthLabels' => $monthLabels,
  'months' => $months,
  'weekdayCounts' => $weekdayCounts,
  'availableYears' => $availableYears,
  'year' => $year,
  'semester' => $semester,
  'monthStart' => $monthStart,
  'monthEnd' => $monthEnd,
  'bulanNames' => $bulanNames,
])
@endsection