@extends('layouts.tablerpublic')

@section('content')
@include('publicviews.statistik.partials.berusaha-stats', [
  'pageTitle' => 'Statistik Publik NIB',
  'pageDescription' => 'Ringkasan data NIB berdasarkan skala usaha, status penanaman modal, dan jenis perusahaan.',
  'primaryMetricLabel' => 'Total NIB Tahun ' . $year,
  'primaryMetricValue' => number_format($total ?? 0),
  'primaryMetricNote' => 'Total NIB pada tahun terpilih.',
  'secondaryMetricLabel' => 'Total Periode Tampil',
  'secondaryMetricValue' => number_format($totalTerbit ?? 0),
  'secondaryMetricNote' => 'Sesuai semester yang dipilih.',
  'thirdMetricLabel' => 'Email / Telepon',
  'thirdMetricValue' => number_format($emailTersedia ?? 0) . ' / ' . number_format($teleponTersedia ?? 0),
  'thirdMetricNote' => 'Kontak perusahaan yang tersedia.',
  'fourthMetricLabel' => 'Status PM Terdeteksi',
  'fourthMetricValue' => number_format($statusAktif ?? 0),
  'fourthMetricNote' => 'Rekaman status penanaman modal.',
  'categoryTitle' => 'Top Skala Usaha',
  'categorySubtitle' => 'Distribusi skala usaha pemohon.',
  'categoryAllTitle' => 'Daftar skala usaha NIB',
  'secondaryTitle' => 'Top Status PM',
  'secondarySubtitle' => 'Status penanaman modal terbanyak.',
  'secondaryAllTitle' => 'Daftar status penanaman modal',
  'monthlyTitle' => 'Jumlah NIB per Bulan',
  'yearlyTitle' => 'NIB per tahun',
  'secondaryYearlyTitle' => 'Jenis perusahaan per tahun',
  'stackedTitle' => 'Komposisi skala usaha per bulan',
  'donutTitle' => 'Top skala usaha',
  'detailModalTitle' => 'Rincian skala usaha',
  'detailColumnLabel' => 'Skala Usaha',
  'categoryRows' => $stats,
  'secondaryRows' => $secondaryStats,
  'topItems' => $topKategori,
  'detailDataByMonth' => [],
  'secondarySeriesByYear' => $secondarySeriesByYear,
  'allSecondary' => $allSecondary,
  'allKategori' => $allKategori,
  'kategoriSeries' => $kategoriSeries,
  'monthlyCounts' => $monthlyCounts,
  'yearlyCounts' => $yearlyCounts,
  'monthLabels' => $monthLabels,
  'months' => $months,
  'weekdayCounts' => $weekdayCounts,
  'availableYears' => $availableYears,
  'year' => $year,
  'semester' => $semester,
  'monthStart' => $monthStart,
  'monthEnd' => $monthEnd,
  'bulanNames' => $bulanNames,
])
@endsection