@extends('layouts.tablerpublic')

@section('content')
@include('publicviews.statistik.partials.berusaha-stats', [
  'pageTitle' => 'Statistik Publik Proyek',
  'pageDescription' => 'Ringkasan data proyek perizinan berusaha berdasarkan skala usaha, risiko, dan sektor pembina.',
  'primaryMetricLabel' => 'Total Proyek Tahun ' . $year,
  'primaryMetricValue' => number_format($total ?? 0),
  'primaryMetricNote' => 'Total proyek pada tahun terpilih.',
  'secondaryMetricLabel' => 'Total Periode Tampil',
  'secondaryMetricValue' => number_format($totalTerbit ?? 0),
  'secondaryMetricNote' => 'Sesuai semester yang dipilih.',
  'thirdMetricLabel' => 'Total Investasi',
  'thirdMetricValue' => 'Rp ' . number_format($totalInvestasi ?? 0, 0, ',', '.'),
  'thirdMetricNote' => 'Akumulasi nilai investasi proyek.',
  'fourthMetricLabel' => 'Total TKI / NIB',
  'fourthMetricValue' => number_format($totalTki ?? 0) . ' / ' . number_format($totalNib ?? 0),
  'fourthMetricNote' => 'Tenaga kerja dan NIB unik.',
  'categoryTitle' => 'Top Skala Usaha',
  'categorySubtitle' => 'Kelompok skala usaha terbanyak.',
  'categoryAllTitle' => 'Daftar skala usaha proyek',
  'secondaryTitle' => 'Top Risiko Proyek',
  'secondarySubtitle' => 'Risiko proyek paling dominan.',
  'secondaryAllTitle' => 'Daftar risiko proyek',
  'monthlyTitle' => 'Jumlah Proyek per Bulan',
  'yearlyTitle' => 'Proyek per tahun',
  'secondaryYearlyTitle' => 'Sektor pembina per tahun',
  'stackedTitle' => 'Komposisi skala usaha per bulan',
  'donutTitle' => 'Top skala usaha',
  'detailModalTitle' => 'Rincian skala usaha',
  'detailColumnLabel' => 'Skala Usaha',
  'categoryRows' => $stats,
  'secondaryRows' => $secondaryStats,
  'topItems' => $topKategori,
  'detailDataByMonth' => [],
  'secondarySeriesByYear' => $secondarySeriesByYear,
  'allSecondary' => $allSecondary,
  'allKategori' => $allKategori,
  'kategoriSeries' => $kategoriSeries,
  'monthlyCounts' => $monthlyCounts,
  'yearlyCounts' => $yearlyCounts,
  'monthLabels' => $monthLabels,
  'months' => $months,
  'weekdayCounts' => $weekdayCounts,
  'availableYears' => $availableYears,
  'year' => $year,
  'semester' => $semester,
  'monthStart' => $monthStart,
  'monthEnd' => $monthEnd,
  'bulanNames' => $bulanNames,
])
@endsection